### ISSUE TITLE
Please support OAuth 2.0 scopes

### ISSUE THREAD

**Issue by stefano-m** [globocom/aio-alf#2]
Hello,

thanks for creating aio-alf.

I have noticed that there is no way for `TokenManager` to send the `scope`[1] parameter in its token request:

https://github.com/globocom/aio-alf/blob/200ecb68eade5b3756e74730d5c8e2f63b9713fd/aioalf/manager.py#L52

Specifying the scopes is quite useful and I was wondering whether this functionality could be added to the library.

As a (quite ugly) workaround, I have overridden the `_request_token` method in a custom token manager class and using it in a custom subclass of `Client`.

https://github.com/globocom/aio-alf/blob/200ecb68eade5b3756e74730d5c8e2f63b9713fd/aioalf/client.py#L15

What do you think about optionally passing the scopes to the `Client` so it can forward them to its token manager?

Many thanks

[1] https://tools.ietf.org/html/rfc6749#section-3.3

**Comment by pedrokiefer** [comment]
That's definitely missing. Any hints on how the API should look like? Just add a scope parameter to the `Client` constructor?

**Comment by stefano-m** [comment]
Hello,

yes, I was thinking that an optional `scope` parameter in `Client` should be fine.

Considering that `scope` can actually be multiple scopes, I would pass something like a list of strings to the `Client`'s constructor and then join them with a `+` sign in the `TokenManager`.

Note that the string must be percent-encoded before being sent to the server. Maybe one could use Python's `urllib.parse.urlencode` or similar. Unless this is already done in `aiohttp`?

Thanks!

**Comment by pedrokiefer** [comment]
@stefano-m just pushed cbb81d449d9b7210d5ad3dcfe2e947cd400807db with the scope implementation, can you review before I make a release?

**Comment by stefano-m** [comment]
Thanks! Will try an have a look soon.
