### ISSUE TITLE
Debugging output exposes authorization token in Authorization header

### ISSUE THREAD

**Issue by stefano-m** [globocom/aio-alf#3]
Hello,

when turning on debugging, `aioalf` logs the `Authorization` header of the request, thus disclosing private credentials.

I would like to suggest that such header is filtered before logging so credentials are not exposed (this is a security best practice).

For example, one could log the first 5 and last 2 characters of the token, something like:

```
DEBUG:aioalf.client:Header Authorization: Bearer abcde<...>fg
```

This happens in both the client and the manager:

https://github.com/globocom/aio-alf/blob/200ecb68eade5b3756e74730d5c8e2f63b9713fd/aioalf/client.py#L59

https://github.com/globocom/aio-alf/blob/200ecb68eade5b3756e74730d5c8e2f63b9713fd/aioalf/manager.py#L77

I may be able to submit a PR if you are willing to take it.

Thanks

**Comment by pedrokiefer** [comment]
I'm willing to take a PR on this if you can submit one.

**Comment by pedrokiefer** [comment]
Just pushed 65f609086d916a5e65bc96845b80d7700166ab7b with a filter for authorization header.
